name: C/C++ CI

on:
  push:
    branches: [ ci-test ]
  pull_request:
    branches: [ ci-test ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: git
      run: |
        git config --global user.email "ci@postgrespro.ri"
        git config --global user.name "CI PgPro admin"
        git clone https://github.com/postgres/postgres.git pg
        cd pg
        git checkout master
        git subtree add --prefix=contrib/aqo https://github.com/postgrespro/aqo.git master
        patch -p1 --no-backup-if-mismatch < contrib/aqo/aqo_master.patch
        ./configure
        make -C contrib/aqo check
        make -C contrib/aqo installcheck
