name: C/C++ CI

on:
  push:
    branches: [ ci-test ]
  pull_request:
    branches: [ ci-test ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: git
      run: |
        git config --global user.email "ci@postgrespro.ri"
        git config --global user.name "CI PgPro admin"
        ls
        git clone https://github.com/postgres/postgres.git pg
        cd pg
        git checkout master
        ./configure --prefix=`pwd`/tmp_install
        make
